version: '3'

services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ../flask-mysql:/Flask_MySQL_App
    container_name: MyFlaskApp
  
    links:
      - MySQLDB:mysql
    depends_on:
      - MySQLDB
  
  MySQLDB:
    image: mysql:5.7.20
    container_name: MyFlaskApp_DB
    environment:
      MYSQL_DATABASE: flask_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
